# This is a basic workflow to help you get started with Actions
name: Ubuntu Aliyunpan image
# Controls when the action will run.
on:
  push:
    branches:
#      - main
      - dev
  pull_request:
    branches:
#      - main
      - dev

jobs:
  buildx:
    runs-on: ubuntu-latest
    environment: env
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d_%H-%M')"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: 'Set Version'
        run: |
          echo "ALIYUNPAN_VER=$(echo `grep -n "ALIYUNPAN_VER=" context/Dockerfile`|awk -F: '{print $2}'|cut -d "=" -f 2)" >> $GITHUB_ENV

      - name: Check version and build
        run: |
          cat previous_ver.txt
          prev_version=$(cat previous_ver.txt)

          if [[ "$previous_version" == "${{ env.ALIYUNPAN_VER }}" ]]; then
            echo "Version unchanged. Skipping build."
            echo "::set-output name=build_required::false"
          else
            echo "Version changed. Building image."
            docker buildx build --load -f ./context/Dockerfile \
            --tag ${{ secrets.REGISTRY }}/${{ secrets.ALIYUNPAN }}:latest \
            --tag ${{ secrets.REGISTRY }}/${{ secrets.ALIYUNPAN }}:${{ env.ALIYUNPAN_VER }} \
            ./context
          fi

      # 只有main分支，并且符合手动推送或定时打包条件时执行推送
      - name: Push Docker image
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || (github.event_name == 'schedule' && github.ref == 'refs/heads/main'))
        run: |
          docker push ${{ secrets.REGISTRY }}/${{ secrets.BEDROCKCONNECT }}:latest
